(def dir "./not-exist-dir/")
(def file (concat dir "not-exist-file.dat"))
(assert (not (io/file-exist? file)))
(io/write-file file "hello")
(assert (= "hello" (bytes2str (io/read-file file))))
(io/write-file file (str2bytes "hello"))
(assert (= "hello" (bytes2str (io/read-file file))))
(assert (io/file-exist? file))
(io/remove-file dir)
(assert (not (io/file-exist? file)))
